version: '3'

services:
  php:
    image: php:8.1.18-fpm
    volumes:
      - './sapper:/var/www/html'
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './sapper:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'