version: '3'

services:
  php:
    image: php:8.1.18-fpm
    volumes:
      - './sapper:/var/www/html'
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - './sapper:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
#      - ./certbot/www:/var/www/certbot/:ro
#      - ./certbot/conf/:/etc/nginx/ssl/:ro
#  certbot:
#    image: certbot/certbot:latest
#    volumes:
#      - ./certbot/www/:/var/www/certbot/:rw
#      - ./certbot/conf/:/etc/letsencrypt/:rw
